export const PLANS = [
  {
    id: "free",
    name: "Free",
    tagline: "For individuals trying things out",
    price: "$0",
    priceSub: "forever",
    cta: "Get started",
    highlight: false,
    features: [
      "1 project",
      "Up to 3 team members",
      "Community support",
      "1 GB storage",
    ],
  },
  {
    id: "starter",
    name: "Starter",
    tagline: "For small teams getting going",
    price: "$19",
    priceSub: "/ month",
    cta: "Start free trial",
    highlight: false,
    features: [
      "5 projects",
      "Up to 10 team members",
      "Email support",
      "10 GB storage",
      "Basic analytics",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    tagline: "For growing teams that need more",
    price: "$49",
    priceSub: "/ month",
    cta: "Start free trial",
    highlight: true,
    features: [
      "Unlimited projects",
      "Up to 50 team members",
      "Priority support",
      "100 GB storage",
      "Advanced analytics",
      "Custom integrations",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    tagline: "For orgs with custom needs",
    price: "Custom",
    priceSub: "",
    cta: "Contact sales",
    highlight: false,
    features: [
      "Unlimited everything",
      "Unlimited team members",
      "Dedicated support",
      "Custom storage",
      "SSO & audit logs",
      "Custom contract & SLA",
    ],
  },
];
